name: Actions Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v9.3

      - name: List all modified files
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
          done
        env:
          FILE_CONT: ${{toJSON(steps.changed-files.outputs.all_modified_files)}}
          run: echo "$FILE_CONT"
      - name: List files in the repository
        run: |
            python ./.github/workflows/build.py
